FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SignIn

## SignIn [/signin]

### sign in the account [POST]

+ Request (application/json)

        {
            "username":"zhang3"
            "password":"zhang3"
        }
+ Response 200 (application/json)

    + Headers

            Location: /admins
            Cookie: {"token" : "abcd"}

    + Body

            {
                "code": 200,
                "enmsg": "ok",
                "cnmsg": "成功",
                "data": null
            }


## SignOut [/signout]

### sign out the account [GET]

+ Response 200 (application/json)

    + Headers

            Location: /
            Cookie: {"token" : null}

    + Body

            {
                "code": 200,
                "enmsg": "ok",
                "cnmsg": "成功",
                "data": null
            }